apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: my-first-app
  labels:
    app: mongodb
spec:
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
        - name: mongo-data 
          persistentVolumeClaim:
            claimName: mongodb-pv-claim
      containers:
      - name: mongodb
        image: {{ .Values.mongodb.image }}
        ports:
        - containerPort: {{ .Values.mongodb.port }}
        volumeMounts:
          - name: mongo-data
            mountPath: /data/db
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: my-first-app
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}